parameters:
  docker:
    client:
      service:
        gerrit:
          environment:
            #GERRIT_INIT_ARGS: ""
            DATABASE_TYPE: "mysql"
            DB_PORT_3306_TCP_ADDR: ${_param:cluster_vip_address}
            DB_ENV_MYSQL_USER: gerrit
            DB_ENV_MYSQL_PASSWORD: ${_param:mysql_gerrit_password}
            DB_ENV_MYSQL_DB: gerrit
            AUTH_TYPE: ${_param:gerrit_auth_type}
            WEBURL: ${_param:gerrit_public_host}
            GERRIT_ADMIN_SSH_PUBLIC: ${_param:gerrit_admin_public_key}
            GERRIT_ADMIN_PWD: ${_param:gerrit_admin_password}
            GERRIT_ADMIN_EMAIL: ${_param:gerrit_admin_email}
          restart:
            condition: any
          image: ${_param:docker_image_gerrit}
          ports:
            - 18083:8080
            - 29417:29418
          volume:
            site:
              type: bind
              source: /srv/volumes/gerrit
              destination: /var/gerrit/review_site
