parameters:
    _param:
      alertmanager_notification_pushkin_host: ${_param:haproxy_pushkin_bind_host}
      alertmanager_notification_pushkin_port: ${_param:haproxy_pushkin_bind_port}
parameters:
  prometheus:
    alertmanager:
      config:
        route:
          group_by: ['region', 'service']
          group_wait: 60s
          group_interval: 5m
          repeat_interval: 3h
          receiver: pushkin_notification
          routes:
            - match:
                route: email
              receiver: email_notification
            - match:
                route: salesforce
              receiver: salesforce_notification
        receivers:
          - name: salesforce_notification
            webhook_configs:
              - url: "${_param:alertmanager_notification_pushkin_host}:${_param:alertmanager_notification_pushkin_port}/webhook?app=stacklight&route=salesforce&cluster_id=id"
                send_resolved: true
          - name: pushkin_notification
            webhook_configs:
              - url: "${_param:alertmanager_notification_pushkin_host}:${_param:alertmanager_notification_pushkin_port}/webhook?app=stacklight&route=email&cluster_id=id"
                send_resolved: true
