parameters:
  jenkins:
    client:
      job_template:
        docker-build-images-opencontrail:
          name: "docker-build-images-opencontrail-{{version}}"
          jobs:
            - version: oc40
          template:
            discard:
              build:
                keep_num: 25
              artifact:
                keep_num: 25
            type: workflow-scm
            concurrent: true
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/docker-opencontrail"
              credentials: "gerrit"
            trigger:
              gerrit:
                project:
                  "mk/docker-opencontrail":
                    branches:
                      - master
                event:
                  ref:
                    - updated: {}
                  comment:
                    - addedContains:
                        commentAddedCommentContains: '(buildcontainer)'
            param:
              IMAGE_GIT_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/docker-opencontrail-{{version}}"
              OC_VERSION:
                type: string
                default: "{{version}}"
              IMAGE_CREDENTIALS_ID:
                type: string
                default: "gerrit"
              IMAGE_TAGS:
                type: string
                default: "latest"
              REGISTRY_URL:
                type: string
                default: ""
              REGISTRY_CREDENTIALS_ID:
                type: string
                default: "dockerhub"
              DOCKER_GIT_TAG:
                type: boolean
                default: "true"
              EXTRA_REPO_URL:
                type: string
                default: "${_param:jenkins_aptly_url}"
