parameters:
  jenkins:
    client:
      job_template:
        docker-build-image-testing:
          name: docker-build-image-{{name}}-{{branch}}
          jobs:
            - name: python-flask-hello
              branch: "master"
              tags: "latest"
              dockerfile: "Dockerfile"
          template:
            discard:
              build:
                keep_num: 5
              artifact:
                keep_num: 5
            type: workflow-scm
            concurrent: true
            scm:
              type: git
              url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
              credentials: "gerrit"
              script: docker-build-image-pipeline.groovy
            trigger:
              reverse:
                projects:
                  - build-debian-python-flask-hello-ubuntu-trusty
                state: UNSTABLE
            param:
              IMAGE_NAME:
                type: string
                default: "tcpcloud/{{name}}"
              IMAGE_GIT_URL:
                type: string
                default: "${_param:jenkins_gerrit_url}/mk/python-flask-hello"
              IMAGE_BRANCH:
                type: string
                default: "{{branch}}"
              IMAGE_CREDENTIALS_ID:
                type: string
                default: "gerrit"
              IMAGE_TAGS:
                type: string
                default: "{{tags}}"
              DOCKERFILE_PATH:
                type: string
                default: "{{dockerfile}}"
              REGISTRY_URL:
                type: string
                default: ""
              REGISTRY_CREDENTIALS_ID:
                type: string
                default: "dockerhub"
              DOCKER_GIT_TAG:
                type: boolean
                default: "true"
