parameters:
  linux:
    system:
      config:
        jenkins_master:
          grains:
            fqdn: dummy
          pillar:
            jenkins:
              master:
                home: /srv/volumes/jenkins
      sudo:
        users:
          jenkins:
            hosts:
            - ALL
            commands:
            - docker