parameters:
  _param:
    prometheus_glusterfs_service_host: ${_param:glusterfs_service_host}
  glusterfs:
    client:
      volumes:
        prometheus-config:
          path: /srv/volumes/prometheus-config
          server: ${_param:prometheus_glusterfs_service_host}
          opts: 'defaults'
