parameters:
  _param:
    opencontrail_control_node01_hostname: ntw01
    opencontrail_control_node02_hostname: ntw02
    opencontrail_control_node03_hostname: ntw03
  opencontrail:
    client:
      config_node:
        member01:
          name: ${_param:opencontrail_control_node01_hostname}
          ip_address: ${_param:cluster_node01_address}
        member02:
          name: ${_param:opencontrail_control_node02_hostname}
          ip_address: ${_param:cluster_node02_address}
        member03:
          name: ${_param:opencontrail_control_node03_hostname}
          ip_address: ${_param:cluster_node03_address}
