parameters:
  _param:
    docker_image_jenkins: tcpcloud/jenkins:2.63
  docker:
    client:
      stack:
        jenkins:
          service:
            master:
              environment:
                JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Dhudson.footerURL=https://www.mirantis.com"
                JENKINS_NUM_EXECUTORS: 4
              deploy:
                restart_policy:
                  condition: any
              image: ${_param:docker_image_jenkins}
              ports:
                - 18081:8080
                - 50001:50000
              volumes:
                - /srv/volumes/jenkins:/var/jenkins_home
                - /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts:ro
