parameters:
  _param:
    salt_control_trusty_image: http://apt.tcpcloud.eu/images/ubuntu-14-04-x64-201608231134.qcow2
    salt_control_xenial_image: http://apt.tcpcloud.eu/images/ubuntu-16-04-x64-201608231004.qcow2
    aptly_gpg_keypair_id: 6SD11111
    aptly_gpg_public_key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1

      mQINBFhFXEcBEAC2eZaWZf9IKDfMfZHtpYukJbm6704Tzk/mTVfgtd8p9jevMvTI
      PihmP5k90OxPbI3ofqT5d1AsSpbyd80bHGPld2Fxop67X1VX4ZKPGEZS3qsfSwUD
      qdHEmF0P0YfTRHzsnDKy+7UOv+9c9qpeexfSmwh+tpIeGQ2RWSSYLTLaLYvm1632
      k2suaVUs+h2wvHB2FiJ9              fsGXp5qo1GmPdxW2jp+qU4qlKOPPGf
      aOn6pTiqUo488Z9AtIra    FIXME     jcoOrcWUT7P9nDmo4cCQ00Dtt7pA7d
      k2suaVUs+h2wvHB2FiJ9              fsGXp5qo1GmPdxW2jp+qU4qlKOPPGf
      E1MMAmc8TCdpBLVLlbCSP697IRhWfOpO+rkv0fnYZUKsBw8uQhLih+zUsSrNmQ+x
      E1MMAmc8TCdpBLVLlbCSP697IRhWfOpO+rkv0fnYZUKsBw8uQhLih+zUsSrNmQ+x
      5qDF9X5GhMws5YfNKcan4tCbXokv8uJpl5fV1yWg+nY5cckX/Q==
      =oz8L
      -----END PGP PUBLIC KEY BLOCK-----
    aptly_gpg_private_key: |
      -----BEGIN PGP PRIVATE KEY BLOCK-----
      Version: GnuPG v1

      lQcXBFhFXEcBEAC2eZaWZf9IKDfMfZHtpYukJbm6704Tzk/mTVfgtd8p9jevMvTI
      PihmP5k90OxPbI3ofqT5d1AsSpbyd80bHGPld2Fxop67X1VX4ZKPGEZS3qsfSwUD
      qdHEmF0P0YfTRHzsnDKy+7UOv+9c9qpeexfSmwh+tpIeGQ2RWSSYLTLaLYvm1632
      k2suaVUs+h2wvHB2FiJ9              fsGXp5qo1GmPdxW2jp+qU4qlKOPPGf
      aOn6pTiqUo488Z9AtIra    FIXME     jcoOrcWUT7P9nDmo4cCQ00Dtt7pA7d
      k2suaVUs+h2wvHB2FiJ9              fsGXp5qo1GmPdxW2jp+qU4qlKOPPGf
      QLSK2jXNuMYm83/asBRo3KDq3FlE+z/Zw5qOHAkNNA7be6QO3RNTDAJnPEwnaQS1
      S5Wwkj+veyEYVnzqTvq5L9H52GVCrAcPLkIS4ofs1LEqzZkPseagxfV+RoTMLOWH
      zSnGp+LQm16JL/LiaZeX1dcloPp2OXHJF/0=
      =N+hS
      -----END PGP PRIVATE KEY BLOCK-----
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - cfg01
          - cfg01.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_compute_node01_address}
          names:
          - kvm01
          - kvm01.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_compute_node02_address}
          names:
          - kvm02
          - kvm02.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_compute_node03_address}
          names:
          - kvm03
          - kvm03.${_param:cluster_domain}
        sto01:
          address: ${_param:infra_storage_node01_single_address}
          names:
          - sto01
          - sto01.${_param:cluster_domain}
        git01:
          address: ${_param:infra_version_control_node01_single_address}
          names:
          - git01
          - git01.${_param:cluster_domain}
        cid01:
          address: ${_param:infra_integration_node01_single_address}
          names:
          - cid01
          - cid01.${_param:cluster_domain}
        bmk01:
          address: ${_param:infra_benchmark_node01_single_address}
          names:
          - bmk01
          - bmk01.${_param:cluster_domain}
