classes:
- system.linux.system.repo_local.tcp-extra
- system.openssh.client.lab
- system.jenkins.master.single
- system.jenkins.client.single
- cluster.ci_infra
parameters:
  _param:
    jenkins_admin_password: cloudlab
    jenkins_admin_password_hash: b029a1661slkdjfksdjfdsjflsjdfslfdsfhdsfjdjflksjdlkfjdslkjfdd85b6
    jenkins_admin_token: cdsf4kdjsdkjfkdsjfsjsa
  linux:
    network:
      interface:
        ens2: ${_param:linux_dhcp_interface}
        ens3: ${_param:linux_single_interface}
    system:
      package:
        python-docutils:
          version: latest
        build-essential:
          version: latest
  jenkins:
    client:
      master:
        host: localhost
        port: 8080
        protocol: http
        username: admin
        password: ${_param:jenkins_admin_password}
      source:
        bear:
          engine: git
          address: git@git01.infra.ci.local:jenkins-jobs/acme-jobs.git
          branch: master
      job:
        bear-env-create:
          type: workflow
          display_name: "Waterbear: Start service in new Heat environment"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
            salt_username:
              type: string
              default: "salt"
              description: "Salt master user"
            salt_password: "cloudlab"
              typer: string
              default: "bear123"
              description: "Salt master password"
            centos_image:
              type: choice
              default: "centos-6"
              description: "Stack context: Instance image"
              choices:
              - "centos-6"
              - "centos-7"
              - "centos6-new"
              - "CentOS-6-x86_64-GenericCloud-1607"
            instance_flavor:
              type: string
              default: "m1.large"
              description: "Stack context: Instance flavor"
            volume_type:
              type: string
              default: "10kThinPro"
              description: "Stack context: Volume type"
            public_net:
              type: string
              default: "inet2"
              description: "Stack context: Network name"
            config_host:
              type: string
              default: "10.167.0.5"
              description: "Stack context: Configuration server"
            domain_name:
              type: string
              default: "bear-single.ci.local"
              description: "Stack context: Instance domain name"
            template_repository:
              type: choice
              default: "git@ci.local:heat-templates"
              description: "Template source: Repository URL"
              choices:
              - "git@git.tcpcloud.eu:heat-templates/telekomsk-templates.git"
              - "git@ci.local:heat-templates"
            template_file:
              type: choice
              default: "template/bear_single_net.hot"
              description: "Template source: File in repository"
              choices:
              - "template/bear_aio_net.hot"
              - "template/bear_single_net.hot"
              - "template/bear_cluster_net.hot"
              - "template/bear_database_net.hot"
              - "template/bear_search_net.hot"
            template_branch:
              type: string
              default: "master"
              description: "Template source: Repository branch"
            openstack_endpoint:
              type: choice
              default: "http://10.171.20.60:5000/v2.0"
              description: "OpenStack endpoint: API host"
              choices:
              - "http://10.171.20.60:5000/v2.0"
              - "https://vpc.tcpisek.cz:5000/v2.0"
            openstack_version:
              type: string
              default: "kilo"
              description: "OpenStack endpoint: Client versions"
            openstack_tenant:
              type: choice
              default: bear-dev
              description: "OpenStack endpoint: Tenant name"
              choices:
              - bear-dev
              - tcp_wb_stg
            openstack_user:
              type: choice
              default: "developer1"
              description: "OpenStack endpoint: Username"
              choices:
              - developer1
              - bear
            openstack_password: cloudlab
              type: choice
              default: "developer1"
              description: "OpenStack endpoint: Password"
              choices:
              - developer1
              - heslo12345
            heat_stack_name:
              type: string
              default: test_stack_name
              description: "Heat stack name"
            stack_size:
              type: choice
              default: medium
              choices:
              - small
              - medium
              - large 
              description: "Instance sizes"
            stack_template:
              type: choice
              default: single
              choices:
              - aio
              - single
              - cluster
              description: "Stack template"
            ext_services:
              type: choice
              default: dev
              choices:
              - dev
              - stg
              - pub
              description: "Generic environmental parameters"
            build_version:
              type: string
              default: "RC_2016_08_A_V02"
              description: Liferay_portal application artefact builds from this version
            db_content:
              type: string
              default: content
              description: Name of the database dump to restore
            report_email:
              type: string
              default: "akomarek@mirantis.com"
              description: E-mail address to send the workflow results
            availability_zone:
              type: string
              default: AZ_PROD
              description: Availability zone for created nodes
          libs:
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/salt.groovy
          - repository: bear
            file: macros/openstack.groovy
          - repository: bear
            file: macros/python.groovy
          - repository: bear
            file: macros/common.groovy
          script:
            repository: bear
            file: workflows/bear_create_env.groovy
        bear-env-update:
          type: workflow
          display_name: "Waterbear: Update service packages in environment"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
            salt_username:
              type: string
              default: salt
              description: "Salt master user"
            salt_password: cloudlab
              type: string
              default: bear123
              description: "Salt master password"
            openstack_endpoint:
              type: choice
              default: "http://10.171.20.60:5000/v2.0"
              description: "OpenStack endpoint: API host"
              choices:
              - "http://10.171.20.60:5000/v2.0"
              - "https://vpc.tcpisek.cz:5000/v2.0"
            openstack_version:
              type: string
              default: "kilo"
              description: "OpenStack endpoint: Client versions"
            openstack_tenant:
              type: string
              default: tcp_wb_stg
              description: "OpenStack endpoint: Tenant name"
            openstack_user:
              type: string
              default: bear
              description: "OpenStack endpoint: Username"
            openstack_password: cloudlab
              type: string
              default: heslo12345
              description: "OpenStack endpoint: Password"
            heat_stack_name:
              type: string
              default: test_stack_name
              description: "Heat stack name"
            report_email:
              type: string
              default: ales.komarek@tcpcloud.eu
              description: E-mail address to send the workflow results
          libs:
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/salt.groovy
          - repository: bear
            file: macros/openstack.groovy
          - repository: bear
            file: macros/python.groovy
          - repository: bear
            file: macros/common.groovy
          script:
            repository: bear
            file: workflows/bear_update_env.groovy
        bear-service-upgrade:
          type: workflow
          display_name: "Waterbear: Upgrade running service in heat environment"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
            salt_username:
              type: string
              default: salt
              description: "Salt master user"
            salt_password: cloudlab
              type: string
              default: bear123
              description: "Salt master password"
            openstack_endpoint:
              type: string
              default: "https://vpc.tcpisek.cz:5000/v2.0"
              description: "OpenStack endpoint: API host"
            openstack_version:
              type: string
              default: "kilo"
              description: "OpenStack endpoint: Client versions"
            openstack_tenant:
              type: string
              default: tcp_wb_stg
              description: "OpenStack endpoint: Tenant name"
            openstack_user:
              type: string
              default: bear
              description: "OpenStack endpoint: Username"
            openstack_password: cloudlab
              type: string
              default: heslo12345
              description: "OpenStack endpoint: Password"
            heat_stack_name:
              type: string
              default: test_stack_name
              description: "Heat stack name"
            build_version:
              type: string
              default: "1.2.3"
              description: Liferay_portal application artefact deploys from this version
            report_email:
              type: string
              default: ales.komarek@tcpcloud.eu
              description: E-mail address to send the workflow results
          libs:
          - repository: bear
            file: macros/common.groovy
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/salt.groovy
          - repository: bear
            file: macros/python.groovy
          - repository: bear
            file: macros/openstack.groovy
          script:
            repository: bear
            file: workflows/bear_upgrade_system.groovy
        bear-app-build:
          type: workflow
          display_name: "Waterbear: Build application WARs from source"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
            salt_username:
              type: string
              default: salt
              description: "Salt master user"
            salt_password: cloudlab
              type: string
              default: bear123
              description: "Salt master password"
            source_repository:
              type: choice
              default: "git@ci.local:skstbear"
              choices:
              - "git@ci.local:skstbear"
              - "git@git.tcpcloud.eu:python-apps/stskbear.git"
              description: "Application artefacts to build from this repository"
            source_branch:
              type: string
              default: RB_2016_08_A
              description: application artefact to build from this branch
            build_version:
              type: string
              default: RB_2016_08_A
              description: Liferay_portal application artefact build from this version
            storage_server_host:
              type: string
              default: 172.16.10.100
              description: "Storage server: Host name"
            storage_server_path:
              type: string
              default: '/srv/salt/env/dev/liferay-portal-source/war'
              description: "Storage server: Filesystem path"
            storage_server_user:
              type: string
              default: salt
              description: "Storage server: Storage user"
            report_email:
              type: string
              default: ales.komarek@tcpcloud.eu
              description: E-mail address to send the workflow results
          libs:
          - repository: bear
            file: macros/common.groovy
          - repository: bear
            file: macros/java.groovy
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/python.groovy
          - repository: bear
            file: macros/openstack.groovy
          script:
            repository: bear
            file: workflows/bear_build_app.groovy
        bear-database-dump:
          type: workflow
          display_name: "Waterbear: Dump and store database from environment"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
            salt_username:
              type: string
              default: salt
              description: "Salt master user"
            salt_password: cloudlab
              type: string
              default: "bear123"
              description: "Salt master password"
            openstack_endpoint:
              type: string
              default: "https://vpc.tcpisek.cz:5000/v2.0"
              description: "OpenStack endpoint: API host"
            openstack_version:
              type: string
              default: "kilo"
              description: "OpenStack endpoint: Client versions"
            openstack_tenant:
              type: string
              default: tcp_wb_stg
              description: "OpenStack endpoint: Tenant name"
            openstack_user:
              type: string
              default: bear
              description: "OpenStack endpoint: Username"
            openstack_password: cloudlab
              type: string
              default: heslo12345
              description: "OpenStack endpoint: Password"
            heat_stack_name:
              type: string
              default: test_stack_name
              description: "Heat stack name"
            data_scrable:
              type: bool
              default: false
              description: Liferay_portal application artefact build from this version
            report_email:
              type: string
              default: ales.komarek@tcpcloud.eu
              description: E-mail address to send the workflow results
          libs:
          - repository: bear
            file: macros/common.groovy
          - repository: bear
            file: macros/salt.groovy
          - repository: bear
            file: macros/openstack.groovy
          - repository: bear
            file: macros/java.groovy
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/python.groovy
          script:
            repository: bear
            file: workflows/bear_build_app.groovy
