classes:
- system.linux.system.repo_local.tcp-extra
- system.openssh.client.lab
- system.jenkins.master.single
- system.jenkins.client.single
- cluster.ci_infra
parameters:
  _param:
    jenkins_admin_password: cloudlab
    jenkins_admin_password_hash: b029a1661slkdjfksdjfdsjflsjdfslfdsfhdsfjdjflksjdlkfjdslkjfdd85b6
    jenkins_admin_token: cdsf4kdjsdkjfkdsjfsjsa
  linux:
    network:
      interface:
        ens2: ${_param:linux_dhcp_interface}
        ens3: ${_param:linux_single_interface}
    system:
      package:
        python-docutils:
          version: latest
        build-essential:
          version: latest
  jenkins:
    client:
      master:
        host: localhost
        port: 8080
        protocol: http
        username: admin
        password: ${_param:jenkins_admin_password}
      source:
        bear:
          engine: git
          address: git@git01.infra.ci.local:jenkins-jobs/acme-jobs.git
          branch: master
      job:
        bear-env-create:
          type: workflow
          display_name: "bear: Start service in new Heat environment"
          param:
            salt_url:
              type: string
              default: "http://172.16.10.100:8000"
              description: "Salt master URL"
          libs:
          - repository: bear
            file: macros/git.groovy
          - repository: bear
            file: macros/salt.groovy
          - repository: bear
            file: macros/openstack.groovy
          - repository: bear
            file: macros/python.groovy
          - repository: bear
            file: macros/common.groovy
          script:
            repository: bear
            file: workflows/bear_update_env.groovy
