classes:
- system.linux.system.repo_local.mos8
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.salt.control.cluster.opencontrail_analytics_cluster
- system.salt.control.cluster.opencontrail_control_cluster
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
- system.salt.control.cluster.openstack_benchmark_single
- system.salt.control.cluster.openstack_billing_single
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- system.salt.control.cluster.infra_storage_single
- system.salt.control.cluster.infra_version_control_single
- system.salt.control.cluster.infra_integration_single
- cluster.ci_infra
parameters:
  _param: 
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 20
    cluster_vip_address: ${_param:infra_compute_address}
    cluster_local_address: ${_param:single_address}
    cluster_node01_hostname: kvm01
    cluster_node01_address: ${_param:infra_compute_node01_address}
    cluster_node02_hostname: kvm02
    cluster_node02_address: ${_param:infra_compute_node02_address}
    cluster_node03_hostname: kvm03
    cluster_node03_address: ${_param:infra_compute_node03_address} 
  virt:
    nic:
      default:
        eth1:
          bridge: br_mgm
          model: virtio
        eth0:
          bridge: br_ctl
          model: virtio
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
        openstack.control:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        openstack.proxy:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 8
          ram: 32768
          disk_profile: small
          net_profile: default
        opencontrail.analytics:
          cpu: 8
          ram: 32768
          disk_profile: large
          net_profile: default
        stacklight.log:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: default
        stacklight.server:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: default
        #openstack.telemetry is correct in system
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}
  linux:
    network:
      interface:
        eth0:
          enabled: true
          type: eth
          proto: manual
        eth1:
          enabled: true
          type: eth
          proto: manual
        eth2:
          enabled: true
          type: eth
          proto: manual
        eth3:
          enabled: true
          type: eth
          proto: manual
        eth4:
          enabled: true
          type: slave
          master: bond0
        eth5:
          enabled: true
          type: slave
          master: bond0
        eth6:
          enabled: true
          type: slave
          master: bond1
        eth7:
          enabled: true
          type: slave
          master: bond1
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - eth4
          - eth5
          slaves: eth4 eth5
          mode: active-backup
        bond1:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - eth6
          - eth7
          slaves: eth6 eth7
          mode: active-backup
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: 255.255.255.0
          use_interfaces:
          - eth0
        br_ctl: 
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          gateway: 10.167.4.1
          netmask: 255.255.255.0
          name_servers:
          - 10.170.7.31
          - 10.168.7.31
          use_interfaces:
          - bond0
        br_data:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:data_address}
          netmask: 255.255.255.0
          use_interfaces:
          - bond1
    system:
      package:
        multipath-tools:
          version: latest
        multipath-tools-boot:
          version: latest 
    storage:
      enabled: true
      multipath:
        enabled: true
        blacklist_devices:
        - /dev/sda
        #- ${_param:second_local_disk}